from lens_solver import solve_lens_parameters_from_obs, compute_detJ
from scipy.interpolate import interp1d
import numpy as np

def solve_lens_tabulate(...): ...
def detJ_tabulate(...): ...
def build_interp_list_for_lenses(data_df, logMh_grid, zl=0.3, zs=2.0): ...
